"""initial models: fan, wristband, stagezone, performanceslot, ticketbooking

Revision ID: a39d57168534
Revises: 
Create Date: 2026-08-01 04:48:02.358258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39d57168534'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fans',
    sa.Column('fan_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('fan_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('stage_zones',
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('vip_access', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_table('performance_slots',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('performance_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['stage_zones.zone_id'], ),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_table('wristbands',
    sa.Column('wristband_id', sa.Integer(), nullable=False),
    sa.Column('fan_id', sa.Integer(), nullable=False),
    sa.Column('chip_code', sa.String(), nullable=False),
    sa.Column('activation_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['fan_id'], ['fans.fan_id'], ),
    sa.PrimaryKeyConstraint('wristband_id'),
    sa.UniqueConstraint('chip_code'),
    sa.UniqueConstraint('fan_id')
    )
    op.create_table('ticket_bookings',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('fan_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('tier_name', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('booking_status', sa.String(), nullable=False),
    sa.Column('booked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fan_id'], ['fans.fan_id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['performance_slots.slot_id'], ),
    sa.PrimaryKeyConstraint('booking_id'),
    sa.UniqueConstraint('fan_id', 'slot_id', 'tier_name', name='uq_fan_slot_tier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_bookings')
    op.drop_table('wristbands')
    op.drop_table('performance_slots')
    op.drop_table('stage_zones')
    op.drop_table('fans')
    # ### end Alembic commands ###
